name: JMeter Test Pipeline

on:
  push:
    branches:
      - main  # Rodar quando houver push na branch principal
  pull_request:
    branches:
      - main  # Rodar quando houver pull request para a branch principal

jobs:
  jmeter-test:
    runs-on: ubuntu-latest  # Rodar no Ubuntu mais recente
    
    steps:
      # Passo 1: Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Passo 2: Instalar o Java (necessário para o JMeter)
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      # Passo 3: Instalar o JMeter
      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
          tar -xvzf apache-jmeter-5.4.1.tgz
          export JMETER_HOME=$(pwd)/apache-jmeter-5.4.1
          export PATH=$JMETER_HOME/bin:$PATH
          
      # Passo 4: Rodar os testes JMeter
      - name: Run JMeter test
        run: |
          $JMETER_HOME/bin/jmeter -n -t "Consulta de CEP.jmx" -l result.jtl -e -o report

      # Passo 5: Upload de artefatos (relatórios)
      - name: Upload JMeter report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: report/
